
# machine fixture for debug purpose

newmach = {'billingItem': {'orderItem': {'categoryCode': 'guest_core',
                               'description': '1 x 2.0 GHz Core',
                               'domainName': 'dev.wearelearning.com',
                               'hostName': 'walo3',
                               'hourlyRecurringFee': '.025',
                               'id': 107936067,
                               'itemId': 857,
                               'itemPriceId': '51027',
                               'laborAfterTaxAmount': '0',
                               'laborFee': '0',
                               'laborFeeTaxRate': '0',
                               'laborTaxAmount': '0',
                               'oneTimeAfterTaxAmount': '0',
                               'oneTimeFee': '0',
                               'oneTimeFeeTaxRate': '0',
                               'oneTimeTaxAmount': '0',
                               'order': {'accountId': 299987,
                                         'createDate': '2016-02-09T15:37:30+01:00',
                                         'id': 6888983,
                                         'impersonatingUserRecordId': '',
                                         'modifyDate': '2016-02-09T15:37:39+01:00',
                                         'orderQuoteId': '',
                                         'orderTypeId': 4,
                                         'presaleEventId': '',
                                         'privateCloudOrderFlag': False,
                                         'status': 'APPROVED',
                                         'userRecord': {'username': 'sl-orchestra'},
                                         'userRecordId': 205472},
                               'parentId': '',
                               'promoCodeId': '',
                               'quantity': '',
                               'recurringAfterTaxAmount': '0',
                               'recurringFee': '0',
                               'recurringTaxAmount': '0',
                               'setupAfterTaxAmount': '0',
                               'setupFee': '0',
                               'setupFeeDeferralMonths': 12,
                               'setupFeeTaxRate': '0',
                               'setupTaxAmount': '0'},
                 'recurringFee': '.025'},
 'blockDeviceTemplateGroup': {'globalIdentifier': 'defc87e3-9b4e-4cdb-bcd7-a1a9153c043d',
                              'id': 933511,
                              'name': '040216-NODE2'},
 'blockDevices': [{'bootableFlag': 1,
                   'createDate': '2016-02-09T15:38:53+01:00',
                   'device': '0',
                   'diskImageId': 13339187,
                   'guestId': 15860379,
                   'hotPlugFlag': 0,
                   'id': 20364459,
                   'modifyDate': '',
                   'mountMode': 'RW',
                   'mountType': 'Disk',
                   'statusId': 1,
                   'uuid': '97e64d8c-4c21-6fa6-bbe0-c3b0d9525265'},
                  {'bootableFlag': 0,
                   'createDate': '2016-02-09T15:38:59+01:00',
                   'device': '1',
                   'diskImageId': 13339207,
                   'guestId': 15860379,
                   'hotPlugFlag': 0,
                   'id': 20364489,
                   'modifyDate': '',
                   'mountMode': 'RW',
                   'mountType': 'Disk',
                   'statusId': 1,
                   'uuid': 'd6240be8-0e69-4e79-7d83-ab0d2b48144a'}],
 'createDate': '2016-02-09T15:37:30+01:00',
 'datacenter': {'id': 449500,
                'longName': 'Paris 1',
                'name': 'par01',
                'statusId': 2},
 'dedicatedAccountHostOnlyFlag': False,
 'domain': 'dev.wearelearning.com',
 'fullyQualifiedDomainName': 'walo3.dev.wearelearning.com',
 'globalIdentifier': 'dba94142-d4b1-4022-be23-24a2d8e7d31e',
 'hostname': 'walo3',
 'hourlyBillingFlag': True,
 'id': 15860379,
 'maxCpu': 1,
 'maxMemory': 1024,
 'modifyDate': '2016-02-09T15:44:21+01:00',
 'networkComponents': [{'id': 8194107,
                        'macAddress': '06:66:ba:f3:0a:13',
                        'maxSpeed': 10,
                        'name': 'eth',
                        'port': 0,
                        'primaryIpAddress': '10.126.19.186',
                        'primarySubnet': {'addressSpace': 'PRIVATE',
                                          'broadcastAddress': '10.126.19.191',
                                          'cidr': 26,
                                          'gateway': '10.126.19.129',
                                          'id': 739334,
                                          'isCustomerOwned': False,
                                          'isCustomerRoutable': False,
                                          'modifyDate': '2015-04-19T01:14:17+00:00',
                                          'netmask': '255.255.255.192',
                                          'networkIdentifier': '10.126.19.128',
                                          'networkVlanId': 700368,
                                          'sortOrder': '4',
                                          'subnetType': 'PRIMARY',
                                          'totalIpAddresses': 64,
                                          'usableIpAddressCount': 61,
                                          'version': 4},
                        'speed': 10,
                        'status': 'ACTIVE'},
                       {'id': 8194109,
                        'macAddress': '06:28:82:6f:c6:b7',
                        'maxSpeed': 0,
                        'name': 'eth',
                        'port': 1,
                        'speed': 0,
                        'status': 'DISABLED'}],
 'networkVlans': [{'id': 700368,
                   'networkSpace': 'PRIVATE',
                   'vlanNumber': 861}],
 'operatingSystem': {'hardwareId': '',
                     'id': 9201667,
                     'manufacturerLicenseInstance': '',
                     'passwords': [{'password': 'S26Js4pY',
                                    'username': 'root'}],
                     'softwareLicense': {'id': 1523,
                                         'softwareDescription': {'manufacturer': 'Debian',
                                                                 'name': 'Debian',
                                                                 'referenceCode': 'DEBIAN_7_64',
                                                                 'version': '7.0.0-64 Minimal for VSI'},
                                         'softwareDescriptionId': 1163}},
 'powerState': {'keyName': 'RUNNING', 'name': 'Running'},
 'primaryBackendIpAddress': '10.126.19.186',
 'privateNetworkOnlyFlag': True,
 'provisionDate': '2016-02-09T15:44:21+01:00',
 'status': {'keyName': 'ACTIVE', 'name': 'Active'},
 'tagReferences': [{'id': 10476965, 'tag': {'id': 484793, 'name': 'walams'}}],
 'userData': []}

