
* SLAPY : Softlayer servers orchestration with haproxy, ansible and munin

slapy is a python program that manage the insertion and removal of instanciated 
server clones in the HAproxy load balancer and munin configurations as soon as they are ready.
Servers are grouped by pool based on the first tag of any SL VSI image.
A few set of operations are automatized through ansible and they can play nice
with a continuous integration process, such for dispatching payloads to the servers 
(new raised ones or existing ones)

** Post pop operations

A call to slapy usually goes this way :
=slapy pop -c machconfig -m 3 -s postpop.py=
will instantiate 3 servers defined in =VM/configVSI.py=
#+begin_src python
sshkeys = [00001,00002]
class ServerConfig :
  configParams = {
    'tags': 'mach,foo' # the first one is the pool
    'domain': "domain.net",
    'cpus': 1,
    'memory': 1024,
    'datacenter':"ams01",
    'hourly': True,
    'private_vlan': 100008,
    'private': True,
    'ssh_keys': sshkeys
  }
#+end_src

*the first tag is important* : it defines the pool name, 
which is used for backend, hostnames and images.

An instance will be raised by looking into the list of saved image
for more recent image named after the pool name.
In the above example, 3 machines are raised, mach[1-3] 
from the last image saved with name =mach=.
The script =postPop.py= insert them in the appropriate section of
an haproxy configuration and munin configurations into =munin.d/=

** HAproxy configurations

=haproxy.cfg= is generated by concatenating in this order
- =haproxy.conf= : it holds the base configuration
- =haproxy/haproxy.d= : anything under this is configured according to what's in =genHAconfig.py=
  that is, prefix and suffix of the servers that are inserted in the backends :
  =server IP :port check maxconn 450= for instance.

*** Backends
Each backend is defined by BACKEND.POOL in =slapy/haproxy/haproxy.d=.
For instance a backend defined as =foo.bar= is meant for machines 
tagged as =bar= that will get inserted in the backend =foo=.
#+begin_src
# example for a backend configuration 
backend foo
   balance roundrobin
   http-check disable-on-404
   http-check expect status 200
   option tcp-smart-connect
   option splice-response
   # the servers will follows from here as :
   # bar1 IP options
   # bar2 IP options
#+end_src

*** hosts
The list of servers ip to insert automatically goes into =haproxy/hosts=
as =POOL.ips=. This means that if you defined two backends in
=haproxy/haproxy.d= as =foo.pool= and =bar.pool=, adding a server inside
the pool will push it to both backends. 
Making a symbolic =haproxy/hosts/server.ips= link to a file =slapy/hosts/server.ips=
will make the new instances recorded in the haproxy configuration when it's regenerated.

** munin configuration
The hostnames in slapy are generated as poolN where N is the number of machines.
The hosts must be already configured to be munin-nodes.

